### ISSUE TITLE
Cauldron JEI Integration

### ISSUE THREAD

**Issue by NillerMedDild** [KnightMiner/Inspirations#105] opened 2019-01-03 11:45 UTC
Hello!

The Cauldron JEI Integration no longer works in the latest versions of JEI.

Pressing U on a Cauldron yields this:
![billede](https://user-images.githubusercontent.com/21295394/50636185-6e610680-0f55-11e9-88f9-f4da638b674e.png)

Although it does in fact have functional recipes.

## Versions
- Inspirations-1.12.2-0.2.3
- jei_1.12.2-4.14.3.238

**Comment by KnightMiner** [comment] 2019-01-03 14:34
Please give me a copy of your game log, pretty sure this is the same as another reported issue

**Comment by NillerMedDild** [comment] 2019-01-03 17:17
Here you go: https://gist.github.com/NillerMedDild/5b8c033eecd0d3495ad7a5d67e0f7298
I updated JEI to 245, no change.

**Comment by KnightMiner** [comment] 2019-01-03 19:12
Yep, duplicate of #97. You should be able to fix by removing the missing item from the anvil smashing recipes (possibly mulch if you disabled that). I'll have a proper fix along shortly

**Closed by KnightMiner** 2019-01-03 19:12 UTC

**Comment by NillerMedDild** [comment] 2019-01-03 19:46
Oh I see, thank you.
