### ISSUE TITLE
Crash with sodium

### ISSUE THREAD

**Issue by ghost** [KnightMiner/Inspirations#216] opened 2021-07-29 07:16 UTC
Please consider this
https://gist.github.com/ternsip/e50c7bdb060346f8555db867309dbef2

at knightminer.inspirations.tweaks.client.PortalColorHandler.getColor(PortalColorHandler.java:57)
ArrayIndexOutOfBoundsException: -311

https://github.com/spoorn/sodium-forge/issues/92

**Comment by KnightMiner** [comment] 2021-07-29 13:33
This crash report has Sodium written in so many places I cannot reasonably fix it. Wait for them to respond with the solution and if there is something on my side that needs to be done, they can say.

**Comment by ghost** [comment] 2021-08-07 07:05
https://github.com/spoorn/sodium-forge/issues/91
Author said  "This is a compatibility issue with Inspirations from the log"

**Comment by TeamSpen210** [comment] 2021-08-07 21:21
Yes, and that the issue is on Sodium's side, due to a lack of a fallback for one of their optimisations. But it'll be fixed in the next release.

**Comment by KnightMiner** [comment] 2021-12-22 07:22
Fixed in sodium, so closing this.

**Closed as completed by KnightMiner** 2021-12-22 07:22 UTC
Labels: bug, can't fix, compatibility, 1.16
