### ISSUE TITLE
wat.crash

### ISSUE THREAD

**Issue by Sunconure11** [KnightMiner/Inspirations#109] opened 2019-01-29 15:27 UTC
https://paste.dimdev.org/kalolalono.mccrash

**Comment by KnightMiner** [comment] 2019-01-29 16:27
Please give issues useful titles, like "Crash on Startup" at least, I know you can make better issue reports.

This specific crash is caused by someone adding an invalid brewing recipe, they added a null ItemStack and those are no longer supposed to be null. I could fix this, but it's just going to break another mod down the line so you really need to find the broken mod.

**Comment by Sunconure11** [comment] 2019-01-29 22:50
I had updated some mods prior to this crash.

"Updated Dynamic Stealth
Updated FTB Utilities
Updated ModTweaker
Updated Smooth Font"

**Comment by KnightMiner** [comment] 2019-03-09 03:40
Still not much help unless you can narrow it down to a specific mod. I added a catch for this crash, but I can basically guarantee some other mod that uses potions will crash.

**Comment by KnightMiner** [comment] 2019-03-15 04:33
Fixed in 0.2.4

**Closed by KnightMiner** 2019-03-15 04:33 UTC
Labels: compatibility, resolved
