### ISSUE TITLE
anvil doesnt smash blocks

### ISSUE THREAD

**Issue by lordi-erez** [KnightMiner/Inspirations#219] opened 2021-08-26 06:54 UTC
anvil does not smash blocks whatsoever

regadless of height or gamerules

**Comment by KnightMiner** [comment] 2022-11-07 06:23
That feature was never ported to 1.16. So this is not a bug, simply content I am undecided on whether it should return. Going to close this as I am aware I never ported the feature, and it won't be coming to 1.16 (only possibly 1.18+)

**Closed as not planned by KnightMiner** 2022-11-07 06:23 UTC
Labels: bug, 1.16
