### ISSUE TITLE
Anvil Not Working and missing textures

### ISSUE THREAD

**Issue by sweetsosweet** [KnightMiner/Inspirations#30] opened 2018-02-28 04:33 UTC
Hi, I'm having an issue with the anvil not working at all and missing its textures. I can place the anvil, but the gui flashes onscreen for about half a second then doesn't open. I noticed the carpet is missing its textures as well. In my log I've got these lines, which is how I connected it to this mod:

[19:05:47] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `anvil`, expected `inspirations`. This could be a intended override, but in most cases indicates a broken mod.
[19:05:47] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `cauldron`, expected `inspirations`. This could be a intended override, but in most cases indicates a broken mod.
[19:05:47] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `carpet`, expected `inspirations`. This could be a intended override, but in most cases indicates a broken mod.
[19:05:47] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `flower_pot`, expected `inspirations`. This could be a intended override, but in most cases indicates a broken mod.

I am using 1.12.2, forge version 14.23.2.2619, Inspirations-1.12.2-0.1.2

**Comment by KnightMiner** [comment] 2018-02-28 13:12
Please give a full mod list. Does this happen with the latest Forge? With just Inspirations? Are you on a server or single player? Are you using a resource pack?

**Comment by sweetsosweet** [comment] 2018-02-28 21:34
Hi, I'm using the latest version of forge. It seems to be a problem with liteloader only. I'll post my log:

[https://pastebin.com/VvJLQwxe](https://pastebin.com/VvJLQwxe)

**Comment by KnightMiner** [comment] 2018-02-28 21:41
Looks like Liteloader is changing the paths for model loading from the substitutions. I do nothing to change those models specifically. I would report this issue to them since it works with normal Forge. Tell them the issue is with Forge registry substitutions. 

I'll leave this issue open for now, there is a chance I can force the model to load from the proper place.

**Comment by sweetsosweet** [comment] 2018-02-28 21:59
Ok, thanks for your help, I'll bring it up there. :)

**Comment by KnightMiner** [comment] 2018-03-05 20:51
For my future reference: http://develop.liteloader.com/liteloader/LiteLoader/issues/47

**Comment by atxmatt2510** [comment] 2018-03-18 15:56
+1 and subscribing - having the same issue.

**Comment by mezz** [comment] 2018-07-09 00:42
I made a test mod for this here: https://github.com/mezz/LiteLoaderRegistrySubstitutionTest
Looking into it with the sponge devs since I can't get a hold of Mumfrey.

**Comment by asiekierka** [comment] 2019-06-03 00:35
PSA: I have developed a workaround, [available here](https://github.com/mezz/JustEnoughItems/issues/1189#issuecomment-498078956).

**Comment by KnightMiner** [comment] 2021-05-13 23:38
Going to close this as I am done with 1.12 support. If you have this issue, use asie's workaround.

**Closed by KnightMiner** 2021-05-13 23:38 UTC
Labels: 1.12, bug, can't fix, compatibility

**Comment by asiekierka** [comment] 2021-05-14 06:38
It is not an issue on your end anyway; it's perfectly fine to close this. Thank you for your work!
