### ISSUE TITLE
carpet texture is broken for me please healp

### ISSUE THREAD

**Issue by Nazeeh114** [KnightMiner/Inspirations#85] opened 2018-09-01 09:07 UTC
i really love this mod and i really want to play this mod sooooooooooooooooooo bad that i am ready to wash your dirty undies for the rest of my life.

**Comment by KnightMiner** [comment] 2018-09-01 14:00
Do you use LiteLoader? What mod version do you use? What do you mean "broken"? Give some information so I can help you.

**Comment by Nazeeh114** [comment] 2018-09-02 22:42
indeed i use liteloader to get a popup of the enchantments on my weapons and tools. and i am using the latest version that you uploaded to minecraft.curseforge.com. also i am using a resourcepack. without the mod everything is fine. but when i load it with my custom single-player modpack the textures of the carpet and some other textures are reverting to their first state.(aka black-and-purple state)

**Comment by KnightMiner** [comment] 2018-09-02 23:03
This is a known issue with LiteLoader, nothing I can do without removing features as LiteLoader breaks a Forge feature. If you need, you can disable the carpet related feature in my config, but that's about it.

Anyways, duplicate of #30.

**Closed by KnightMiner** 2018-09-02 23:03 UTC

**Comment by Nazeeh114** [comment] 2018-09-02 23:26
i will get back to whether or not if the issue is resolved or not

**Comment by Nazeeh114** [comment] 2018-09-02 23:44
the issue was the same as what you have said
liteloader was the problem
