### ISSUE TITLE
[1.12] Crash on Gamestart (when disabling pipes in the config)

### ISSUE THREAD

**Issue by MasterEnderman** [KnightMiner/Inspirations#76] opened 2018-07-25 01:42 UTC
Forge: 14.23.4.2739
Mantle: 1.3.2.24
Inspirations: 0.2.1
Crash Report: https://paste.dimdev.org/nejowucoqa.mccrash
Config: https://pastebin.com/PYduwZnj

**Comment by KnightMiner** [comment] 2018-07-25 13:31
Duplicate of #70.

**Closed by KnightMiner** 2018-07-25 13:31 UTC
