### ISSUE TITLE
Cauldron fluids option is incompatible with the Rats mod

### ISSUE THREAD

**Issue by Smarteepant** [KnightMiner/Inspirations#131] opened 2019-07-05 02:58 UTC
Mod versions are Inspirations 0.2.4 and Rats 1.1.3.

The extendCauldron option breaks the ability to make cheese by putting milk in a cauldron, probably because Inspirations does a block substitution if extendCauldron is true. Changing the option to "simple" fixes the incompatibility.

**Comment by KnightMiner** [comment] 2019-07-05 03:57
Hmm, this seems like a case of us both doing the same thing, that is both have a feature to put milk in the cauldron. If you disable the Inspirations milk fluid (or fluids in cauldrons in general), does it fix your issue?

**Comment by Smarteepant** [comment] 2019-07-05 18:20
Disabling the Inspirations milk fluid fixed the problem. That was the first thing I tried, but it didn't work because I was using a custom modpack and there was something else messing it up. After slowly adding mods in, I found that Reliquary is the other incompatibility.

To summarize, with just Inspirations and Rats changing milk fluid to false fixes the problem. With Inspirations, Rats, and Reliquary changing extendCauldron to simple fixes the problem (or just disabling Reliquary). Time to go make issues on Reliquary's page now.

Thanks for the help!

**Comment by Smarteepant** [comment] 2019-07-05 18:37
When I tried to completely isolate the issue to between Rats and Reliquary, the milk to cheese recipe worked again. It appears that only when Inspirations, Rats, and Reliquary are all included that the recipe breaks.

The recipe works again when all cauldron fluids are disabled in Inspirations. Only milk needed to be disabled in Inspirations when it was just with Rats.

**Comment by KnightMiner** [comment] 2019-07-05 20:38
The issue is not related to Reliquary, they just also add a milk fluid, which is why is suggested disabling cauldron fluids if the issue still happens with milk disabled.

Your answer gave me enough information, so I'll explain the issue in more detail:
* Inspirations adds a feature where the cauldron can hold any fluid. This means that if any mod adds milk as a fluid, right clicking a cauldron with a milk bucket fills the cauldron
* Inspriations also adds a feature which adds milk as a fluid. Disabling this fixed the issue with just Inspirations as now milk is not a "fluid" so it can't be put in a cauldron. However, when adding Reliquary, milk becomes a fluid again making the bug appear. The same case will happen with any mod that adds milk as a fluid, such as Tinkers Construct, it's not the other mods fault.
* The rats mod adds special behavior when right clicking a cauldron with a vanilla milk bucket. This works when there is no milk fluid because the Inspirations cauldron does not see milk as processable. However, with a milk fluid Inspirations fills the cauldron with milk which prevents Rats from seeing it as an empty cauldron.

As a work around, you can disable fluids in cauldrons. This will prevent things such as stews and juices from being made in the cauldron though, so that's not the best solution

I think I have an idea if how to deal with this, so I'll look into fixing it for the next release.

**Comment by Smarteepant** [comment] 2019-07-06 00:47
I renamed the issue to be more accurate to the actual interaction. Thanks for the great explanation! I didn't notice that Reliquary added milk as a fluid when I looked through the description or the config file, so I didn't realize that's what was happening.

**Comment by KnightMiner** [comment] 2019-07-11 03:35
Fixed in 0.2.5

**Closed by KnightMiner** 2019-07-11 03:35 UTC
Labels: bug, compatibility, resolved
