### ISSUE TITLE
Let us drink ink

### ISSUE THREAD

**Issue by ThugPug43** [KnightMiner/Inspirations#220] opened 2021-09-06 18:30 UTC
**Is your feature request related to a problem? Please describe.**

I get frustrated when trying to make a usable dye and it ends up as an arbitrary color I can only use on leather armor. Then I have a ink I can't really use taking up one of my only bottles

**Describe the idea**
A clear and concise description of your proposed feature.

I think we should be able to drink the ink from the bottles. It wouldn't have any negative side effects it would just be a way to get rid of the ink easily. 

**Describe how you think this feature would fit in vanilla**
Inspirations is designed to contain features that would fit well in vanilla. If it would not fit, describe how it would fit in the mod.

Vanilla lets you eat pufferfish so even if drinking ink is bad it isn't unlike anything in vanilla. Also there is nothing in vanilla in a bottle that you can't drink, even 1/4th of a meter of honey (which has a really gross sound btw).

**Comment by KnightMiner** [comment] 2021-09-07 19:26
If you are trying to delete the ink, you can always break and replace the cauldron. I'll consider another way to empty ink bottles, but that method is ideal.

As for 
> when trying to make a usable dye and it ends up as an arbitrary color

Can you expand upon that? The cauldron does not support mixing colors to get another usable dye at this time, only mixing like leather armor. So mixing red and yellow will not get you the orange dye for instance. Cauldron just lets you "extend dyes" by mixing them with water at this time, which shouldn't be able to produce a non-standard color with just one type.

**Comment by ThugPug43** [comment] 2021-10-28 17:18
I forgot about this my bad. My issue was I was trying to make orange dye and mixed a red and yellow dye bottle in the cauldron. This ended up with an extended dye as you said which couldn't just be picked up to make "Orange Dye" to dye wool or anything else. I called the extended dye arbitrary. That gave me a bunch of bottles with what looked like orange dye but it was unusable for dyeing wool. My suggestion was for an alternate method of ink disposal because getting rid of those "orange" dye bottles was annoying to do. I made around 15 before I realized they weren't actually orange dye usable for wool and terracotta dyeing.

**Comment by KnightMiner** [comment] 2021-10-28 20:13
Yeah, you just described a challenge I never found a good solution for. In theory it would be nice to mix two colors in the cauldron and end up with the "pure dye". In practice, that conflicts with the color value mixing logic. The ideal would be some way to distinguish the two. Either you are mixing pure dyes or you are mixing color values. Just not an easy thing to do without complicating the behavior, might have to settle for special casing certain color combos.

There still is the challenge of dyed bottles in any case, mixing an red dyed bottle with 2 layers of yellow should not give pure orange as the ratio is wrong. Likewise the ratio is wrong if we mix 1 red layer with 1 yellow dye. So we would need to do some math to ensure all of these cases will only ever lead to a loss, never a duplication/direct conversion of dyes (you should not be able to transform red dye into yellow dye, or produce orange from red + yellow at a ratio other than 1:1)

So, if you want that working, going to need some numbers run to determine how strict we need to be before you may mix dyes.

**Comment by SanjivanM** [comment] 2022-01-10 02:00
Could you perhaps add a new Cauldron of sorts that mixes and creates only pure dyes? Something like a "Pure Dye Cauldron" that can only mix to vanilla MC colors, obtained by, for example, placing a Cauldron in a crafting table by itself to convert it to a Pure Dye Cauldron and vice-versa?

**Comment by KnightMiner** [comment] 2022-01-10 02:46
No. I hate the idea of adding a new block for the sake of having a new block. Adding a new magic block to solve the problem is not good design, come up with an interesting way to do it with the existing mechanic.

**Comment by KnightMiner** [comment] 2022-11-07 06:22
Going to close this as the original idea (drinking ink) is not getting added. I do plan on adding some logic to mix dyes into true dyes in the cauldron, but not sure if those plans will pan out.

**Closed as not planned by KnightMiner** 2022-11-07 06:22 UTC
Labels: enhancement, 1.16
