### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by BuilderDan** [KnightMiner/Inspirations#24] opened 2018-02-04 04:32 UTC
Getting this with the latest 1.12 version of the mod:

![image](https://user-images.githubusercontent.com/19805371/35774341-5531f59c-0921-11e8-9c69-9a0dce2904a7.png)

Anvils and carpets have missing textures.

**Comment by KnightMiner** [comment] 2018-02-04 06:05
Going to need more information than that. What version of Forge? Are you on a server? What is the "latest version" exactly?

**Comment by BuilderDan** [comment] 2018-02-04 06:17
Forge version: 2571
Mod version: Inspirations-1.12.2-0.1.1b
Game type: Single player, haven't tested multiplayer.

I removed mods until the problem was resolved, either your mod is conflicting or is the problem itself.
Mod list:
![image](https://user-images.githubusercontent.com/19805371/35774821-01e97568-0930-11e8-9328-c3953890b849.png)
![image](https://user-images.githubusercontent.com/19805371/35774822-04f60988-0930-11e8-90ac-5b2874a29108.png)

**Comment by KnightMiner** [comment] 2018-02-04 06:45
Does this happen with just Inspirations? If not, try and find which combination causes it.

**Comment by BuilderDan** [comment] 2018-02-04 06:51
With only inspirations and mantle installed it still does it.

**Comment by KnightMiner** [comment] 2018-02-04 07:02
Can you try with the latest Forge? It is working for me in a later Forge version than the one you are using.

**Comment by BuilderDan** [comment] 2018-02-04 07:04
If it works for you then it'll work for me, can't use the latest forge though because some mods aren't compatible with it, would it be difficult to have compatibility with forge 2571? Not sure what that would take, but if it is too much effort then don't bother.

**Comment by KnightMiner** [comment] 2018-02-04 07:08
I want to be sure it is the Forge version and not something else, as I know registry overrides can be a bit finicky at times. I am specifically using 2590 right now, so at least try that. Also, I just noticed you have a resource pack in the screenshot, does this happen without the resource pack?

Just trying to narrow down the cause of the issue, which will determine whether I can fix it at all.

**Comment by BuilderDan** [comment] 2018-02-04 07:10
Ok, will do!

**Comment by BuilderDan** [comment] 2018-02-04 08:26
Works fine with forge 2590.

**Comment by BuilderDan** [comment] 2018-02-04 08:31
All my mods seem to be working with that version, so its entirely up to you to fix it for the older version.

**Comment by KnightMiner** [comment] 2018-02-04 15:27
In that case, I am closing this as a Forge bug.

**Closed by KnightMiner** 2018-02-04 15:27 UTC
