### ISSUE TITLE
Attempting to cast Refined Storage Class throws exception

### ISSUE THREAD

**Issue by Mr-Pyro** [KnightMiner/Inspirations#128] opened 2019-06-13 17:42 UTC
https://paste.ubuntu.com/p/yhKBTxfMpW/

`[16:38:45] [Client thread/ERROR] [jei]: Error caught from Recipe Category: knightminer.inspirations.plugins.jei.smashing.SmashingRecipeCategory
java.lang.ClassCastException: com.raoulvdberge.refinedstorage.integration.jei.RecipeWrapperCover cannot be cast to knightminer.inspirations.plugins.jei.smashing.SmashingRecipeWrapper`

**Comment by KnightMiner** [comment] 2019-07-09 22:33
This is definately caused by Refined Storage, the log is littered with errors of trying to cast their recipe to just about every recipe type, making it clear they are somehow adding the recipes wrongly.

**Comment by KnightMiner** [comment] 2019-12-15 06:18
Closing as its caused by another mod and I am not working on 1.12 anymore.

**Closed by KnightMiner** 2019-12-15 06:18 UTC
Labels: can't fix, compatibility
